[package]
name = "mb8c"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
chumsky = { version = "0.11.2" }
logos = { version = "0.16.0" }
mb8-isa = { path = "../mb8-isa" }

[lints]
workspace = true
