[book]
title = "MB8 Documentation"
description = "8bit MicroBot Documentation"
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ya7on/mb8"
site-url = "/mb8/"
